### PR TITLE
Atdgen runtime

### PR DESCRIPTION
**Pull request by rgrinberg**
Okay so this is my attempt at #35. I'm pretty happy with it as it seems to retain full compatibility with old code, and it hides more interfaces from the user. All the code generation stuff is now completely hidden for example. It also lets users specify dependencies more precisely in their opam file:

```
"atdgen" {build}
"atdgen-runtime"
```

And it lets users to eliminate the code generation dependency entirely if they want to vendor the checked in code. In the future, we can even split the runtime into the biniou and yojson components so that users will only use what they generate.

### CODE REVIEW

**Comment by mjambon** [comment]
This looks good to me.

A good thing would be to ensure that the preprocessor emits code that's compatible with the runtime. So far this has been guaranteed by installing both from the same source. Does opam provide a way to constrain `atdgen` to the same version as `atdgen-runtime`? If not, perhaps we should use a contraint of the form `DEPENDENCY {>= MY_VERSION}`.

**Comment by rgrinberg** [comment]
Martin Jambon <notifications@github.com> writes:

> A good thing would be to ensure that the preprocessor emits code
> that's compatible with the runtime. So far this has been guaranteed by
> installing both from the same source. Does opam provide a way to
> constrain `atdgen` to the same version as `atdgen-runtime`?

There's a way to do this in opam 2.0 but IMO this restriction is way too
heavy handed and therefore useless. We should be allowing users to mix
and match different versions of the runtime and the codegen as long as
they are compatible.

> If not, perhaps we should use a contraint of the form `DEPENDENCY {>= MY_VERSION}`.

I'll add a minimum constraint.

**Comment by rgrinberg** [comment]
I added a version constraint. We'll need to release 1.13 for the constraint to make sense. But I suppose that's good anyway.

**Comment by rgrinberg** [comment]
FYI @c-cube you will be able to have a build dependency on `atdgen` following this PR.

**Comment by mjambon** [comment]
Great, thanks!

Let's release 1.13 after #37 is addressed.

**Pull request merged**
