### PR TITLE
Support for rtd generation

### PR DESCRIPTION
**Pull request by rgrinberg**
The switch that I promised before. This is a more integrated documentation
solution. One that we will not have to re-generate and upload manually. We still
need to re-organize the documentation for things to make more sense, but this is
a start. To view the docs locally, you will need to install sphinx and the rtd
theme (read the docs)

### CODE REVIEW

**Comment by rgrinberg** [comment]
Btw, to set up the webhooks for automatic doc generation I will need more permissions to the repo. Or, if you make an account on readthedocs.io, I can add you as a maintainer there and you can setup the webhook yourself.

Once we set everything up: the docs will automatically be built and hosted at: http://atd.readthedocs.io/en/latest/

**Comment by rgrinberg** [comment]
@mjambon ping on this, I just need hook permissions on this repo to set this up.

**Comment by mjambon** [comment]
Ah, sorry, I didn't open the messages from github until today. (Try emailing me directly when I'm blocking you).

So it appears I can't grant you owner or admin status because mjambon is not an organization. I created an `mjambon` account on readthedocs. I'll add the webhook myself after you add me to the readthedocs team.

**Comment by rgrinberg** [comment]
> Ah, sorry, I didn't open the messages from github until today. (Try emailing me directly when I'm blocking you).

Noted.

> So it appears I can't grant you owner or admin status because mjambon is not an organization. I created an mjambon account on readthedocs. I'll add the webhook myself after you add me to the readthedocs team.

Added you as a project maintainer.

**Comment by mjambon** [comment]
If you want we can create a Github organization for atd; I've always felt it's more welcoming to contributors than having projects tied to my name. Github lets us transfer a repo, issues, etc. and takes care of redirects.

**Comment by rgrinberg** [comment]
> If you want we can create a Github organization for atd; I've always felt it's more welcoming to contributors than having projects tied to my name. Github lets us transfer a repo, issues, etc. and takes care of redirects.

This is up to you. Either situation is welcoming to me as a contributor and I encourage you to act in w/e way you think is best for the project.

**Comment by rgrinberg** [comment]
The docs are up!: http://atd.readthedocs.io/en/latest

**Pull request merged**
