### PR TITLE
Code gen polymorphic params with wrapped polymorphic types

### PR DESCRIPTION
**Pull request by struktured**
This PR addresses issue #180 by passing the type parameters to the code which generates the type alias from the unwrapped type to the wrapped type. A provided unit test verifies the fix, but I would appreciate some empirical testing from code reviewers before this gets approved.

### CODE REVIEW

**Comment by struktured** [comment]
@rgrinberg thoughts on this PR?

**Comment by rgrinberg** [comment]
I'll review this next week. Ping me again if I don't get around to it next week.

**Comment by struktured** [comment]
@rgrinberg For some reason git auto closed this PR when I made your suggested changes. Will reopen.

**Comment by struktured** [comment]
@rgrinberg For some reason git auto closed this PR when I made your suggested changes. Will reopen.

**Pull request closed without merging**
